from __future__ import annotations

import asyncio
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table
from sqlalchemy import select

from .core.config import get_settings
from .database import AsyncSessionFactory, engine
from .models.entities import DeviceCategory, DeviceType
from .schemas.base import (
    ComponentTypeCreate,
    DeviceCategoryCreate,
    DeviceTypeCreate,
)
from .services.device_service import (
    create_device_category,
    create_device_type,
    get_alerts,
    get_upcoming_maintenance,
)
from .utils.migrations import run_migrations

app = typer.Typer(help="Management commands for the Ployl backend")
console = Console()


@app.command()
def migrate() -> None:
    """Create database schema."""

    async def _migrate() -> None:
        await run_migrations(engine)

    asyncio.run(_migrate())
    console.print("[green]Migrations completed[/green]")


@app.command()
def upcoming(days: Optional[int] = typer.Option(None, help="Lookahead window in days")) -> None:
    """Show upcoming MTK/STK checks."""

    async def _show() -> None:
        async with AsyncSessionFactory() as session:
            windows = await get_upcoming_maintenance(session, days)
        if not windows:
            console.print("[yellow]No upcoming checks in window[/yellow]")
            return
        table = Table(title="Upcoming Maintenance")
        table.add_column("Device")
        table.add_column("Check")
        table.add_column("Due On")
        table.add_column("Days")
        for window in windows:
            table.add_row(
                window.device_inventory_number,
                window.check_type,
                window.due_on.isoformat(),
                str(window.days_until_due),
            )
        console.print(table)

    asyncio.run(_show())


@app.command()
def alerts(include_resolved: bool = typer.Option(False, help="Show resolved alerts")) -> None:
    """Show maintenance alerts generated by the scheduler."""

    async def _show() -> None:
        async with AsyncSessionFactory() as session:
            alert_rows = await get_alerts(session, include_resolved)
        if not alert_rows:
            console.print("[yellow]No maintenance alerts found[/yellow]")
            return

        table = Table(title="Maintenance Alerts")
        table.add_column("Device")
        table.add_column("Check")
        table.add_column("Due")
        table.add_column("Days")
        table.add_column("Severity")
        table.add_column("Status")

        for alert in alert_rows:
            status_parts = []
            if alert.acknowledged_at:
                status_parts.append("acknowledged")
            if alert.resolved_at:
                status_parts.append("resolved")
            status = ", ".join(status_parts) if status_parts else "open"

            device_label = (
                alert.device.inventory_number if alert.device else str(alert.device_id)
            )
            table.add_row(
                device_label,
                alert.check_type,
                alert.due_on.isoformat(),
                str(alert.days_until_due),
                alert.severity,
                status,
            )
        console.print(table)

    asyncio.run(_show())


@app.command()
def settings() -> None:
    """Display effective configuration."""

    cfg = get_settings()
    table = Table(title="Settings")
    for field, value in cfg.dict().items():
        table.add_row(field, str(value))
    console.print(table)


@app.command()
def seed_products() -> None:
    """Seed standardkategorien und Medizinprodukte."""

    defaults = {
        "Fahrtrage": [
            {"name": "Stryker M1"},
            {"name": "Ferno Monaldy"},
        ],
        "Tragstuhl": [
            {"name": "Dlouhy"},
        ],
        "CO-Warner": [
            {"name": "Dräger PAC 5500"},
            {"name": "Dräger PAC 65000"},
        ],
        "Corpuls": [
            {
                "name": "Corpuls 3",
                "components": [
                    {"name": "Patientenmodul"},
                    {"name": "Therapiemodul"},
                    {"name": "Monitormodul"},
                ],
            }
        ],
    }

    async def _seed() -> None:
        async with AsyncSessionFactory() as session:
            for category_name, products in defaults.items():
                category = await session.execute(
                    select(DeviceCategory).where(DeviceCategory.name == category_name)
                )
                category_obj = category.scalar_one_or_none()
                if not category_obj:
                    category_obj = await create_device_category(
                        session, DeviceCategoryCreate(name=category_name)
                    )
                    await session.flush()

                for product in products:
                    product_stmt = await session.execute(
                        select(DeviceType).where(DeviceType.name == product["name"])
                    )
                    if product_stmt.scalar_one_or_none():
                        continue
                    payload = DeviceTypeCreate(
                        name=product["name"],
                        category_id=category_obj.id,
                        components=[
                            ComponentTypeCreate(**component)
                            for component in product.get("components", [])
                        ],
                    )
                    await create_device_type(session, payload)
            await session.commit()

    asyncio.run(_seed())
    console.print("[green]Standardprodukte angelegt (falls nicht vorhanden).[/green]")


def main() -> None:
    app()


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    main()
